backend:
  name: github
  repo: mompol/mompol.github.io
  branch: main
  site_domain: sparkling-nougat-b1a83a.netlify.com

publish_mode: editorial_workflow
media_folder: "images/uploads"
display_url: https://pfotenklub.de

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "products" 
    label: "Products"
    folder: "_products"
    slug: "{{slug}}"
    create: true 
    fields: 
        - {label: "SKU", name: "sku", widget: "string" }
        - {label: "Price", name: "price", widget: "number"}
        - {label: "Image", name: "image", widget: "string"}
        - {label: "Body", name: "body", widget: "string"}  
        - {label: "Slug", name: "slug", widget: "string" }
        - {label: "Layout", name: "layout", widget: "hidden", default: "productdetails"}
