{\rtf1\ansi\ansicpg1252\cocoartf2638
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier;\f1\fnil\fcharset0 HelveticaNeue-Medium;\f2\fmodern\fcharset0 Courier-Oblique;
}
{\colortbl;\red255\green255\blue255;\red14\green110\blue109;\red255\green255\blue255;\red14\green14\blue14;
\red210\green0\blue53;\red39\green42\blue46;\red135\green136\blue117;}
{\*\expandedcolortbl;;\cssrgb\c0\c50196\c50196;\cssrgb\c100000\c100000\c100000;\cssrgb\c6667\c6667\c6667;
\cssrgb\c86667\c6667\c26667;\cssrgb\c20392\c21961\c23529;\cssrgb\c60000\c60000\c53333;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs30 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 backend\cf4 \strokec4 :\
  \cf2 \strokec2 name\cf4 \strokec4 : \cf5 \strokec5 github\cf4 \strokec4 \
  \cf2 \strokec2 repo\cf4 \strokec4 : \cf5 \strokec5 mompol/mompol.github.io\cf4 \strokec4 \
  \cf2 \strokec2 branch\cf4 \strokec4 : \cf5 \strokec5 master\cf4 \strokec4 \
  \cf2 \strokec2 site_domain\cf4 \strokec4 : 
\f1\b\fs32 \cf6 \cb3 \strokec6 sparkling-nougat-b1a83a.netlify.com
\f0\b0\fs30 \cf4 \cb3 \strokec4 \
\
\cf2 \strokec2 media_folder\cf4 \strokec4 : \cf5 \strokec5 "images/uploads"\cf4 \strokec4 \
\
\cf2 \strokec2 collections\cf4 \strokec4 :\
  - \cf2 \strokec2 name\cf4 \strokec4 : \cf5 \strokec5 "blog"\cf4 \strokec4  
\f2\i \cf7 \strokec7 # Used in routes, e.g., /admin/collections/blog
\f0\i0 \cf4 \strokec4 \
    \cf2 \strokec2 label\cf4 \strokec4 : \cf5 \strokec5 "Blog"\cf4 \strokec4  
\f2\i \cf7 \strokec7 # Used in the UI
\f0\i0 \cf4 \strokec4 \
    \cf2 \strokec2 folder\cf4 \strokec4 : \cf5 \strokec5 "_posts/"\cf4 \strokec4  
\f2\i \cf7 \strokec7 # The path to the folder where the documents are stored
\f0\i0 \cf4 \strokec4 \
    \cf2 \strokec2 create\cf4 \strokec4 : \cf2 \strokec2 true\cf4 \strokec4  
\f2\i \cf7 \strokec7 # Allow users to create new documents in this collection
\f0\i0 \cf4 \strokec4 \
    \cf2 \strokec2 slug\cf4 \strokec4 : \cf5 \strokec5 "\{\{year\}\}-\{\{month\}\}-\{\{day\}\}-\{\{slug\}\}"\cf4 \strokec4  
\f2\i \cf7 \strokec7 # Filename template, e.g., YYYY-MM-DD-title.md
\f0\i0 \cf4 \strokec4 \
    \cf2 \strokec2 fields\cf4 \strokec4 : 
\f2\i \cf7 \strokec7 # The fields for each document, usually in front matter
\f0\i0 \cf4 \strokec4 \
      - \{\cf2 \strokec2 label\cf4 \strokec4 : \cf5 \strokec5 "Title"\cf4 \strokec4 , \cf2 \strokec2 name\cf4 \strokec4 : \cf5 \strokec5 "title"\cf4 \strokec4 , \cf2 \strokec2 widget\cf4 \strokec4 : \cf5 \strokec5 "string"\cf4 \strokec4 \}\
      - \{\cf2 \strokec2 label\cf4 \strokec4 : \cf5 \strokec5 "Publish\cf2 \strokec2  \cf5 \strokec5 Date"\cf4 \strokec4 , \cf2 \strokec2 name\cf4 \strokec4 : \cf5 \strokec5 "date"\cf4 \strokec4 , \cf2 \strokec2 widget\cf4 \strokec4 : \cf5 \strokec5 "datetime"\cf4 \strokec4 \}\
      - \{\cf2 \strokec2 label\cf4 \strokec4 : \cf5 \strokec5 "Tags"\cf4 \strokec4 , \cf2 \strokec2 name\cf4 \strokec4 : \cf5 \strokec5 "tags"\cf4 \strokec4 , \cf2 \strokec2 widget\cf4 \strokec4 : \cf5 \strokec5 "list"\cf4 \strokec4 \}\
      - \{\cf2 \strokec2 label\cf4 \strokec4 : \cf5 \strokec5 "Body"\cf4 \strokec4 , \cf2 \strokec2 name\cf4 \strokec4 : \cf5 \strokec5 "body"\cf4 \strokec4 , \cf2 \strokec2 widget\cf4 \strokec4 : \cf5 \strokec5 "markdown"\cf4 \strokec4 \}\
}